### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lalasou** [Waseh/rclone-unraid#17]
ping -q -c2 8.8.8.8 >/dev/null || ping -q -c2 1.1.1.1 >/dev/null || ping -q -c2 $rcloneurl >/dev/null

**Comment by Waseh** [comment]
This really isn't a very helpful.
What bug do you believe you are experiencing? The above line is working as intended in my testing.

**Comment by lalasou** [comment]
ping: https://downloads.rclone.org/rclone-current-linux-amd64.zip: Name or service not known

**Comment by lalasou** [comment]
or   ping downloads.rclone.org?

**Comment by Waseh** [comment]
You're correct, the ping shouldn't be the full url.
Fixed in [5cb5493](https://github.com/Waseh/rclone-unraid/commit/5cb5493221d4a48c75451857b598e421e9b87599)

**Comment by Waseh** [comment]
Now with fixes for regression introduced in scripts and settings page

**Comment by lalasou** [comment]
OK
