### ISSUE TITLE
Without connecting to the internet, it will cause unraid to start up very slowly!

### ISSUE THREAD

**Issue by lalasou** [Waseh/rclone-unraid#19]
I looked at the code, can you change the part where it updates rclone version at startup? This will cause unraid to take a long time to boot up without connecting to the internet. I think rclone doesn't need to be updated too frequently.

**Comment by lalasou** [comment]
Or, I think you should choose whether to update to the new version of rclone in gui

**Comment by Waseh** [comment]
It adds 30 seconds to the boot sequence on my machine. I don't consider this significant.

**Comment by Waseh** [comment]
Wait a second, there's an error in the script. It should only add 30 seconds but it tries to download rclone even after it already checked there was no internet connection.
I'll fix that.

**Comment by Waseh** [comment]
Thought i had made a mistake in the script but it does in fact only add 30 seconds to my boot time.
Going to close this as not planned.

**Comment by lalasou** [comment]
I just think that rclone doesn't need to check the update every time it is turned on, although 30s is not too long. It is better if users choose to update or not (I think the startup USB flash drive is broken).

**Comment by lalasou** [comment]
In some places where the network environment is not good, downloading rclone will be very slow. My friend said that he could not get into the UI without Unraid, and I found this problem after investigation.

**Comment by lalasou** [comment]
😅
In some places, the international network is not good

It takes about an hour to download 17m ... Yes, you are right.

I changed the code myself, that's all.

**Comment by lalasou** [comment]
I have an Unraid communication community, and I can't get the UI after restarting. I told them to stop using rclone. They all think it's the problem of Unraid, and there's nothing they can do. The quality of the Internet in their area is too poor.
