### ISSUE TITLE
Installation shows error

### ISSUE THREAD

**Issue by hai3009** [Waseh/rclone-unraid#20]
It could be installed before, but now there is an error in the installation. Please solve it.

Verifying package rclone-2024.05.27-bundle.txz.
Installing package rclone-2024.05.27-bundle.txz:
PACKAGE DESCRIPTION:
Package rclone-2024.05.27-bundle.txz installed.
Connection error - Could not reach rclone servers - Will try fallback to existing binary
Install failed - No binary found
plugin: run failed: '/bin/bash' returned 1
Executing hook script: post_plugin_checks

**Comment by Waseh** [comment]
Can you ping downloads.rclone.org? I think the error message is pretty descriptive as to what the problem might be.
